name: CI Learning Docker Notification

on:
    push:
        branches: ["*"]
jobs:
    notify:
        name: CI Learning Docker Notification
        permissions:
            pull-requests: write
        runs-on: docker-runner
        steps:
            - name: Notify
              uses: appleboy/telegram-action@master
              with:
                to: $ {{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: |
                    User: ${{ github.actor }} created commit:
                    Commit message: ${{ github.event.commits[0].message }}
                    
                    Repository: ${{ github.repository }}
                    
                    See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
